<?php

declare(strict_types=1);

return [
    'enabled' => true,

    'steps' => [
        [
            'key' => 'capell-welcome-tour.introduction',
            'title' => 'capell-welcome-tour::welcome_tour.introduction_title',
            'description' => 'capell-welcome-tour::welcome_tour.introduction_description',
            'element' => null,
            'icon' => 'heroicon-o-sparkles',
            'icon_color' => 'primary',
            'sort' => 10,
            'visible' => true,
            'roles' => [],
            'user_created_within_days' => null,
        ],
        [
            'key' => 'capell-welcome-tour.menu',
            'title' => 'capell-welcome-tour::welcome_tour.menu_title',
            'description' => 'capell-welcome-tour::welcome_tour.menu_description',
            'element' => '.fi-sidebar-nav',
            'icon' => 'heroicon-o-bars-3',
            'icon_color' => 'gray',
            'sort' => 20,
            'visible' => true,
            'roles' => [],
            'user_created_within_days' => null,
        ],
        [
            'key' => 'capell-welcome-tour.header-tools',
            'title' => 'capell-welcome-tour::welcome_tour.header_tools_title',
            'description' => 'capell-welcome-tour::welcome_tour.header_tools_description',
            'element' => '.fi-topbar',
            'icon' => 'heroicon-o-wrench-screwdriver',
            'icon_color' => 'gray',
            'sort' => 30,
            'visible' => true,
            'roles' => [],
            'user_created_within_days' => null,
        ],
        [
            'key' => 'capell-welcome-tour.sites',
            'title' => 'capell-welcome-tour::welcome_tour.sites_title',
            'description' => 'capell-welcome-tour::welcome_tour.sites_description',
            'element' => 'a[href*="/sites"]',
            'icon' => 'heroicon-o-globe-alt',
            'icon_color' => 'info',
            'sort' => 35,
            'visible' => true,
            'roles' => [],
            'user_created_within_days' => null,
        ],
        [
            'key' => 'capell-welcome-tour.pages',
            'title' => 'capell-welcome-tour::welcome_tour.pages_title',
            'description' => 'capell-welcome-tour::welcome_tour.pages_description',
            'element' => 'a[href*="/pages"]',
            'icon' => 'heroicon-o-document-text',
            'icon_color' => 'info',
            'sort' => 36,
            'visible' => true,
            'roles' => [],
            'user_created_within_days' => null,
        ],
        [
            'key' => 'capell-welcome-tour.media',
            'title' => 'capell-welcome-tour::welcome_tour.media_title',
            'description' => 'capell-welcome-tour::welcome_tour.media_description',
            'element' => 'a[href*="/media"]',
            'icon' => 'heroicon-o-photo',
            'icon_color' => 'info',
            'sort' => 37,
            'visible' => true,
            'roles' => [],
            'user_created_within_days' => null,
        ],
        [
            'key' => 'capell-welcome-tour.dashboard',
            'title' => 'capell-welcome-tour::welcome_tour.dashboard_title',
            'description' => 'capell-welcome-tour::welcome_tour.dashboard_description',
            'element' => null,
            'icon' => 'heroicon-o-home',
            'icon_color' => 'success',
            'sort' => 50,
            'visible' => true,
            'roles' => [],
            'user_created_within_days' => null,
        ],
    ],

    'contextual_tours' => [
        'capell_admin_sites' => [
            [
                'key' => 'capell-welcome-tour.sites.context.index',
                'title' => 'capell-welcome-tour::welcome_tour.context_sites_index_title',
                'description' => 'capell-welcome-tour::welcome_tour.context_sites_index_description',
                'element' => '.fi-ta, .fi-resource-table, table',
                'icon' => 'heroicon-o-globe-alt',
                'icon_color' => 'info',
                'sort' => 10,
                'visible' => true,
                'roles' => [],
                'user_created_within_days' => null,
            ],
            [
                'key' => 'capell-welcome-tour.sites.context.create',
                'title' => 'capell-welcome-tour::welcome_tour.context_sites_create_title',
                'description' => 'capell-welcome-tour::welcome_tour.context_sites_create_description',
                'element' => 'a[href*="/sites/create"], button[type="submit"]',
                'icon' => 'heroicon-o-plus-circle',
                'icon_color' => 'success',
                'sort' => 20,
                'visible' => true,
                'roles' => [],
                'user_created_within_days' => null,
            ],
        ],
        'capell_admin_pages' => [
            [
                'key' => 'capell-welcome-tour.pages.context.tree',
                'title' => 'capell-welcome-tour::welcome_tour.context_pages_tree_title',
                'description' => 'capell-welcome-tour::welcome_tour.context_pages_tree_description',
                'element' => '.fi-ta, .fi-resource-table, [data-page-tree]',
                'icon' => 'heroicon-o-document-text',
                'icon_color' => 'info',
                'sort' => 10,
                'visible' => true,
                'roles' => [],
                'user_created_within_days' => null,
            ],
            [
                'key' => 'capell-welcome-tour.pages.context.publish',
                'title' => 'capell-welcome-tour::welcome_tour.context_pages_publish_title',
                'description' => 'capell-welcome-tour::welcome_tour.context_pages_publish_description',
                'element' => '[data-publish-action], button[type="submit"]',
                'icon' => 'heroicon-o-rocket-launch',
                'icon_color' => 'success',
                'sort' => 20,
                'visible' => true,
                'roles' => [],
                'user_created_within_days' => null,
            ],
        ],
        'capell_admin_media' => [
            [
                'key' => 'capell-welcome-tour.media.context.library',
                'title' => 'capell-welcome-tour::welcome_tour.context_media_library_title',
                'description' => 'capell-welcome-tour::welcome_tour.context_media_library_description',
                'element' => '.fi-ta, .fi-resource-table, [data-media-library]',
                'icon' => 'heroicon-o-photo',
                'icon_color' => 'info',
                'sort' => 10,
                'visible' => true,
                'roles' => [],
                'user_created_within_days' => null,
            ],
            [
                'key' => 'capell-welcome-tour.media.context.upload',
                'title' => 'capell-welcome-tour::welcome_tour.context_media_upload_title',
                'description' => 'capell-welcome-tour::welcome_tour.context_media_upload_description',
                'element' => 'input[type="file"], [data-media-upload]',
                'icon' => 'heroicon-o-arrow-up-tray',
                'icon_color' => 'success',
                'sort' => 20,
                'visible' => true,
                'roles' => [],
                'user_created_within_days' => null,
            ],
        ],
    ],

    'checklist' => [
        [
            'key' => 'create-site',
            'label' => 'capell-welcome-tour::welcome_tour.checklist_create_site',
            'description' => 'capell-welcome-tour::welcome_tour.checklist_create_site_description',
            'url' => '/admin/sites/create',
            'complete_when' => 'table-has-rows:sites',
        ],
        [
            'key' => 'create-page',
            'label' => 'capell-welcome-tour::welcome_tour.checklist_create_page',
            'description' => 'capell-welcome-tour::welcome_tour.checklist_create_page_description',
            'url' => '/admin/pages/create',
            'complete_when' => 'table-has-rows:pages',
        ],
        [
            'key' => 'upload-media',
            'label' => 'capell-welcome-tour::welcome_tour.checklist_upload_media',
            'description' => 'capell-welcome-tour::welcome_tour.checklist_upload_media_description',
            'url' => '/admin/media',
            'complete_when' => 'table-has-rows:media',
        ],
    ],
];
