<?php

declare(strict_types=1);

return [
    'enabled' => true,

    'steps' => [
        [
            'key' => 'capell-welcome-tour.introduction',
            'title' => 'capell-welcome-tour::welcome_tour.introduction_title',
            'description' => 'capell-welcome-tour::welcome_tour.introduction_description',
            'element' => null,
            'icon' => 'heroicon-o-sparkles',
            'icon_color' => 'primary',
            'sort' => 10,
            'visible' => true,
            'roles' => [],
            'user_created_within_days' => null,
        ],
        [
            'key' => 'capell-welcome-tour.menu',
            'title' => 'capell-welcome-tour::welcome_tour.menu_title',
            'description' => 'capell-welcome-tour::welcome_tour.menu_description',
            'element' => '.fi-sidebar-nav',
            'icon' => 'heroicon-o-bars-3',
            'icon_color' => 'gray',
            'sort' => 20,
            'visible' => true,
            'roles' => [],
            'user_created_within_days' => null,
        ],
        [
            'key' => 'capell-welcome-tour.header-tools',
            'title' => 'capell-welcome-tour::welcome_tour.header_tools_title',
            'description' => 'capell-welcome-tour::welcome_tour.header_tools_description',
            'element' => '.fi-topbar',
            'icon' => 'heroicon-o-wrench-screwdriver',
            'icon_color' => 'gray',
            'sort' => 30,
            'visible' => true,
            'roles' => [],
            'user_created_within_days' => null,
        ],
        [
            'key' => 'capell-welcome-tour.sites',
            'title' => 'capell-welcome-tour::welcome_tour.sites_title',
            'description' => 'capell-welcome-tour::welcome_tour.sites_description',
            'element' => 'a[href*="/sites"]',
            'icon' => 'heroicon-o-globe-alt',
            'icon_color' => 'info',
            'sort' => 35,
            'visible' => true,
            'roles' => [],
            'user_created_within_days' => null,
        ],
        [
            'key' => 'capell-welcome-tour.pages',
            'title' => 'capell-welcome-tour::welcome_tour.pages_title',
            'description' => 'capell-welcome-tour::welcome_tour.pages_description',
            'element' => 'a[href*="/pages"]',
            'icon' => 'heroicon-o-document-text',
            'icon_color' => 'info',
            'sort' => 36,
            'visible' => true,
            'roles' => [],
            'user_created_within_days' => null,
        ],
        [
            'key' => 'capell-welcome-tour.media',
            'title' => 'capell-welcome-tour::welcome_tour.media_title',
            'description' => 'capell-welcome-tour::welcome_tour.media_description',
            'element' => 'a[href*="/media"]',
            'icon' => 'heroicon-o-photo',
            'icon_color' => 'info',
            'sort' => 37,
            'visible' => true,
            'roles' => [],
            'user_created_within_days' => null,
        ],
        [
            'key' => 'capell-welcome-tour.dashboard',
            'title' => 'capell-welcome-tour::welcome_tour.dashboard_title',
            'description' => 'capell-welcome-tour::welcome_tour.dashboard_description',
            'element' => null,
            'icon' => 'heroicon-o-home',
            'icon_color' => 'success',
            'sort' => 50,
            'visible' => true,
            'roles' => [],
            'user_created_within_days' => null,
        ],
    ],

    'checklist' => [
        [
            'key' => 'create-site',
            'label' => 'capell-welcome-tour::welcome_tour.checklist_create_site',
            'description' => 'capell-welcome-tour::welcome_tour.checklist_create_site_description',
            'url' => '/admin/sites/create',
            'complete_when' => 'table-has-rows:sites',
        ],
        [
            'key' => 'create-page',
            'label' => 'capell-welcome-tour::welcome_tour.checklist_create_page',
            'description' => 'capell-welcome-tour::welcome_tour.checklist_create_page_description',
            'url' => '/admin/pages/create',
            'complete_when' => 'table-has-rows:pages',
        ],
        [
            'key' => 'upload-media',
            'label' => 'capell-welcome-tour::welcome_tour.checklist_upload_media',
            'description' => 'capell-welcome-tour::welcome_tour.checklist_upload_media_description',
            'url' => '/admin/media',
            'complete_when' => 'table-has-rows:media',
        ],
    ],
];
