<?php

declare(strict_types=1);
use Capell\Admin\Filament\Pages\ExtensionsPage;
use Capell\Admin\Filament\Resources\Media\MediaResource;
use Capell\Admin\Filament\Resources\Pages\PageResource;
use Capell\Admin\Filament\Resources\Sites\SiteResource;
use Capell\Admin\Filament\Resources\Themes\ThemeResource;

return [
    'enabled' => true,

    'presentation_mode' => false,

    'steps' => [
        [
            'key' => 'capell-welcome-tour.dashboard',
            'title' => 'capell-welcome-tour::welcome_tour.dashboard_title',
            'description' => 'capell-welcome-tour::welcome_tour.dashboard_description',
            'element' => '.fi-page-header, .fi-wi',
            'icon' => 'heroicon-o-home',
            'icon_color' => 'primary',
            'chapter' => 'dashboard',
            'route' => '@dashboard',
            'sort' => 10,
            'visible' => true,
            'roles' => [],
            'user_created_within_days' => null,
        ],
        [
            'key' => 'capell-welcome-tour.sites',
            'title' => 'capell-welcome-tour::welcome_tour.sites_title',
            'description' => 'capell-welcome-tour::welcome_tour.sites_description',
            'element' => '.fi-ta, .fi-resource-table, table',
            'icon' => 'heroicon-o-globe-alt',
            'icon_color' => 'info',
            'chapter' => 'sites',
            'route' => null,
            'resource' => SiteResource::class,
            'sort' => 20,
            'visible' => true,
            'roles' => [],
            'user_created_within_days' => null,
        ],
        [
            'key' => 'capell-welcome-tour.pages',
            'title' => 'capell-welcome-tour::welcome_tour.pages_title',
            'description' => 'capell-welcome-tour::welcome_tour.pages_description',
            'element' => '.fi-ta, .fi-resource-table, [data-page-tree]',
            'icon' => 'heroicon-o-document-text',
            'icon_color' => 'info',
            'chapter' => 'pages',
            'route' => null,
            'resource' => PageResource::class,
            'sort' => 30,
            'visible' => true,
            'roles' => [],
            'user_created_within_days' => null,
        ],
        [
            'key' => 'capell-welcome-tour.themes',
            'title' => 'capell-welcome-tour::welcome_tour.themes_title',
            'description' => 'capell-welcome-tour::welcome_tour.themes_description',
            'element' => '.fi-ta, .fi-resource-table, table',
            'icon' => 'heroicon-o-swatch',
            'icon_color' => 'info',
            'chapter' => 'themes',
            'route' => null,
            'resource' => ThemeResource::class,
            'sort' => 40,
            'visible' => true,
            'roles' => [],
            'user_created_within_days' => null,
        ],
        [
            'key' => 'capell-welcome-tour.media',
            'title' => 'capell-welcome-tour::welcome_tour.media_title',
            'description' => 'capell-welcome-tour::welcome_tour.media_description',
            'element' => '.fi-ta, .fi-resource-table, [data-media-library]',
            'icon' => 'heroicon-o-photo',
            'icon_color' => 'info',
            'chapter' => 'media',
            'route' => null,
            'resource' => MediaResource::class,
            'sort' => 50,
            'visible' => true,
            'roles' => [],
            'user_created_within_days' => null,
        ],
        [
            'key' => 'capell-welcome-tour.publish',
            'title' => 'capell-welcome-tour::welcome_tour.publish_title',
            'description' => 'capell-welcome-tour::welcome_tour.publish_description',
            'element' => '#capell-welcome-tour-checklist',
            'icon' => 'heroicon-o-rocket-launch',
            'icon_color' => 'success',
            'chapter' => 'publish',
            'route' => '@dashboard',
            'sort' => 70,
            'visible' => true,
            'roles' => [],
            'user_created_within_days' => null,
        ],
    ],

    'contextual_tours' => [
        'capell_admin_sites' => [
            [
                'key' => 'capell-welcome-tour.sites.context.index',
                'title' => 'capell-welcome-tour::welcome_tour.context_sites_index_title',
                'description' => 'capell-welcome-tour::welcome_tour.context_sites_index_description',
                'element' => '.fi-ta, .fi-resource-table, table',
                'icon' => 'heroicon-o-globe-alt',
                'icon_color' => 'info',
                'sort' => 10,
                'visible' => true,
                'roles' => [],
                'user_created_within_days' => null,
            ],
            [
                'key' => 'capell-welcome-tour.sites.context.create',
                'title' => 'capell-welcome-tour::welcome_tour.context_sites_create_title',
                'description' => 'capell-welcome-tour::welcome_tour.context_sites_create_description',
                'element' => 'a[href*="/sites/create"], button[type="submit"]',
                'icon' => 'heroicon-o-plus-circle',
                'icon_color' => 'success',
                'sort' => 20,
                'visible' => true,
                'roles' => [],
                'user_created_within_days' => null,
            ],
        ],
        'capell_admin_pages' => [
            [
                'key' => 'capell-welcome-tour.pages.context.tree',
                'title' => 'capell-welcome-tour::welcome_tour.context_pages_tree_title',
                'description' => 'capell-welcome-tour::welcome_tour.context_pages_tree_description',
                'element' => '.fi-ta, .fi-resource-table, [data-page-tree]',
                'icon' => 'heroicon-o-document-text',
                'icon_color' => 'info',
                'sort' => 10,
                'visible' => true,
                'roles' => [],
                'user_created_within_days' => null,
            ],
            [
                'key' => 'capell-welcome-tour.pages.context.publish',
                'title' => 'capell-welcome-tour::welcome_tour.context_pages_publish_title',
                'description' => 'capell-welcome-tour::welcome_tour.context_pages_publish_description',
                'element' => '[data-publish-action], button[type="submit"]',
                'icon' => 'heroicon-o-rocket-launch',
                'icon_color' => 'success',
                'sort' => 20,
                'visible' => true,
                'roles' => [],
                'user_created_within_days' => null,
            ],
        ],
        'capell_admin_media' => [
            [
                'key' => 'capell-welcome-tour.media.context.library',
                'title' => 'capell-welcome-tour::welcome_tour.context_media_library_title',
                'description' => 'capell-welcome-tour::welcome_tour.context_media_library_description',
                'element' => '.fi-ta, .fi-resource-table, [data-media-library]',
                'icon' => 'heroicon-o-photo',
                'icon_color' => 'info',
                'sort' => 10,
                'visible' => true,
                'roles' => [],
                'user_created_within_days' => null,
            ],
            [
                'key' => 'capell-welcome-tour.media.context.upload',
                'title' => 'capell-welcome-tour::welcome_tour.context_media_upload_title',
                'description' => 'capell-welcome-tour::welcome_tour.context_media_upload_description',
                'element' => 'input[type="file"], [data-media-upload]',
                'icon' => 'heroicon-o-arrow-up-tray',
                'icon_color' => 'success',
                'sort' => 20,
                'visible' => true,
                'roles' => [],
                'user_created_within_days' => null,
            ],
        ],
    ],

    'checklist' => [
        [
            'key' => 'create-page',
            'label' => 'capell-welcome-tour::welcome_tour.checklist_create_page',
            'description' => 'capell-welcome-tour::welcome_tour.checklist_create_page_description',
            'url' => '/admin/pages/create',
            'complete_when' => 'table-has-rows:pages',
            'resource' => PageResource::class,
        ],
        [
            'key' => 'create-site',
            'label' => 'capell-welcome-tour::welcome_tour.checklist_create_site',
            'description' => 'capell-welcome-tour::welcome_tour.checklist_create_site_description',
            'url' => '/admin/sites',
            'complete_when' => 'table-has-rows:sites',
            'resource' => SiteResource::class,
        ],
        [
            'key' => 'pick-theme',
            'label' => 'capell-welcome-tour::welcome_tour.checklist_pick_theme',
            'description' => 'capell-welcome-tour::welcome_tour.checklist_pick_theme_description',
            'url' => '/admin/themes',
            'complete_when' => 'non-default-theme',
            'resource' => ThemeResource::class,
        ],
        [
            'key' => 'extend',
            'label' => 'capell-welcome-tour::welcome_tour.checklist_extend',
            'description' => 'capell-welcome-tour::welcome_tour.checklist_extend_description',
            'url' => '/admin/extensions',
            'complete_when' => '',
            'resource' => ExtensionsPage::class,
        ],
    ],
];
